import React from "react";
export const metadata = {
  title: "About Me",
  description: "Generated by create next app",
};
const page = () => {
  return <div className="text-pink-800">page</div>;
};

export default page;
