import { Poppins } from "next/font/google"; // Change import to Poppins
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
}); // Change variable name to poppins

export const metadata = {
  title: "Moustafa El-Sayed | Frontend and Mobile App Developer | Portfloi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
