import React from 'react'
export const metadata = {
  title: "My Project",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>page</div>
  )
}

export default page